Face Liveness Detection
yashasvini121/predictive-calc pull request #104
Opened 2024-10-08 23:23 UTC by ananyag309

#68 the model i have added verify whether a person is physically present during the authentication process by analyzing facial features and eye blinks. 🔍

### Checklist

- [ ] My code follows the current [project structure](https://github.com/yashasvini121/predictive-calc/blob/master/docs/project-structure.md)
- [ ] I have thoroughly reviewed and updated the `requirements.txt` file to include any new packages
- [ ] The `predict.py` file includes a properly implemented `model_details()` function, or the notebook contains this function to print a detailed model report. **The model will not be accepted without this function**, as it is essential for generating the necessary model details.
- [ ] I have added relevant tests (if necessary).
- [ ] I have added comments in the code where needed.
- [ ] This PR is submitted under **Hacktoberfest**.
- [ ] This PR is submitted under **GirlScript Summer of Code (GSSoC-Extd)**.

2024-10-09 16:23 UTC, Pranshu-jais commented
@ananyag309  Please  add  Streamlit page   under pages/  directory

2024-10-11 16:06 UTC, yashasvini121 requested changes
Your work is incomplete, make the requested changes and create a page for your model.

2024-10-11 16:06 UTC, yashasvini121 commented on models/Face Liveness Detection/requirements.txt
Don't create a separate requirements.txt file, update the existing one.

2024-10-11 16:06 UTC, yashasvini121 commented on models/Face Liveness Detection/main.py
Follow the project structure.

2024-10-11 16:06 UTC, yashasvini121 commented on models/Face Liveness Detection/dataset/haarcascade_frontalface_default.xml
Save it in saved/models and change it to csv format

2024-10-11 16:10 UTC, ananyag309 commented on models/Face Liveness Detection/requirements.txt
dobe

2024-10-11 16:21 UTC, ananyag309 commented
@yashasvini121 can you please help me? i have converted xml file to csv and deleted requirement.txt what else need to be done

2024-10-14 15:02 UTC, yashasvini121 commented
@ananyag309, you can check the documentation to see if it helps. Additionally, in the `emotion-detection` branch, the [emotion detection model](https://github.com/yashasvini121/predictive-calc/tree/emotion-detector/models/emotion_detector) utilizes the camera feature, so you might find it useful to refer to that as well.

2024-10-26 09:26 UTC, ananyag309 commented
@yashasvini121 I have completed all the necessary requirements. If everything looks good, please proceed with merging them.

2024-10-26 11:58 UTC, closed without merging