Text Summarization Model
yashasvini121/predictive-calc pull request #147
Opened 2024-10-14 17:27 UTC by Peart-Guy

### Description
I added a Text Summarizer Model 
Name: Ankan
Github: Peart-Guy
Participant role: GSSOC-24 EXTD , Hacktoberfest

### Issue Resolved
#139 

### Changes Made
I added a new model which summarizes long texts that enhances understanding and speed up learning—perfect for students and professionals alike.

### Screenshots or Videos

https://github.com/user-attachments/assets/5b00cfe0-2dff-4790-b88b-7cc1647f0460

### Additional Details

### Checklist

- [x] My code follows the current [project structure](https://github.com/yashasvini121/predictive-calc/blob/master/docs/project-structure.md)
- [x] I have thoroughly reviewed and updated the `requirements.txt` file to include any new packages
- [ ] The `predict.py` file includes a properly implemented `model_details()` function, or the notebook contains this function to print a detailed model report. **The model will not be accepted without this function**, as it is essential for generating the necessary model details.
- [x] I have added relevant tests (if necessary).
- [x] I have added comments in the code where needed.
- [x] This PR is submitted under **Hacktoberfest**.
- [x] This PR is submitted under **GirlScript Summer of Code (GSSoC-Extd)**.

2024-10-15 05:07 UTC, Peart-Guy commented
@yashasvini121  I have done my work. Kindly check it out and give GSSOC-24 EXTD, Hacktoberfest and Level 3. It will be an honor

2024-10-15 05:42 UTC, yashasvini121 requested changes
Your work in not in the correct project structure. Please refer docs/

2024-10-15 07:55 UTC, Peart-Guy commented
> Your work in not in the correct project structure. Please refer docs/

Since my program is a NLP model so it is done in a single file and it does not need any separate code file to train or a separate code file to run or a separate file of data sets @yashasvini121

2024-10-15 18:36 UTC, yashasvini121 requested changes
Your final submission should include the following:  
1. An independent `predict.py` file using **Streamlit**.  
2. Your page added to the `pages.json` configuration.  
3. Your form configurations defined in `form_config`.  
4. Utilization of the `page_handler` class to generate your page.  

Check docs in case, I've missed anything, but these are the primary requirements.

2024-10-15 18:36 UTC, yashasvini121 commented on models/text_sumarization/predict.py
The `predict.py` and `pages/text_summarizer.py` files contain identical code. Please remove the Streamlit-related code from `predict.py`. You don't need to manually create the page—use the `page_handler` class to generate it. Refer `docs/`

2024-10-15 18:37 UTC, yashasvini121 commented
Feel free to reach out if you have any questions regarding the expected changes.

2024-10-16 07:48 UTC, Peart-Guy commented
> Feel free to reach out if you have any questions regarding the expected changes.

@yashasvini121 
Since my project comes with the built in UI so it is completed in one single file. My project does not need separate predict.py file or separate UI file. It will completely run by the Text Summarizer.py in the pages folder 


I hope I was able to explain everything clearly.  Would you like any further adjustments?

2024-10-16 18:20 UTC, yashasvini121 commented
> > Feel free to reach out if you have any questions regarding the expected changes.
> 
> @yashasvini121 Since my project comes with the built in UI so it is completed in one single file. My project does not need separate predict.py file or separate UI file. It will completely run by the Text Summarizer.py in the pages folder
> 
> I hope I was able to explain everything clearly. Would you like any further adjustments?

Your project works fine, but please note that the PR checklist specifies that the required project structure must be followed. If not, your PR will only receive a Level 1 rating.

2024-10-16 18:37 UTC, Peart-Guy commented
> > > Feel free to reach out if you have any questions regarding the expected changes.
> > 
> > 
> > @yashasvini121 Since my project comes with the built in UI so it is completed in one single file. My project does not need separate predict.py file or separate UI file. It will completely run by the Text Summarizer.py in the pages folder
> > I hope I was able to explain everything clearly. Would you like any further adjustments?
> 
> Your project works fine, but please note that the PR checklist specifies that the required project structure must be followed. If not, your PR will only receive a Level 1 rating.



@yashasvini121 
But I don't have extra files to add ,to maintain the project structure.
Kindly understand that  my project is designed to be simple and efficient, requiring only a single file to function perfectly. This streamlined approach reflects my preference for minimalistic programming, ensuring both ease of maintenance and clarity in structure.
I trust that I have clearly explained the issue, and I am confident that you will understand my perspective.
Thank You

2024-10-18 11:58 UTC, Peart-Guy commented
> > > > Feel free to reach out if you have any questions regarding the expected changes.
> > > 
> > > 
> > > @yashasvini121 Since my project comes with the built in UI so it is completed in one single file. My project does not need separate predict.py file or separate UI file. It will completely run by the Text Summarizer.py in the pages folder
> > > I hope I was able to explain everything clearly. Would you like any further adjustments?
> > 
> > 
> > Your project works fine, but please note that the PR checklist specifies that the required project structure must be followed. If not, your PR will only receive a Level 1 rating.
> 
> @yashasvini121 But I don't have extra files to add ,to maintain the project structure. Kindly understand that my project is designed to be simple and efficient, requiring only a single file to function perfectly. This streamlined approach reflects my preference for minimalistic programming, ensuring both ease of maintenance and clarity in structure. I trust that I have clearly explained the issue, and I am confident that you will understand my perspective. Thank You



@yashasvini121 I hope you understood. Will be waiting for your reply
Thank You

2024-10-19 07:53 UTC, yashasvini121 approved these changes

2024-10-19 08:24 UTC, merged

2024-10-19 11:10 UTC, Peart-Guy commented
@yashasvini121  Thank You for Understanding. It was pleasure working with you.