added the main.py and readme along with dataset file
yashasvini121/predictive-calc pull request #207
Opened 2024-11-07 15:06 UTC by Dharun235

### Description

This project utilizes a Random Forest Classifier for binary classification, which is effective for structured data and allows us to evaluate feature importance. Random Forest is suitable for this problem because it handles various customer data types (e.g., demographics, account details, and service usage) and helps identify key factors contributing to churn. The model provides a clear, interpretable outcome, highlighting the primary attributes associated with churn behavior.

### Issue Resolved

#205 

### Changes Made

Added the main.py, dataset.csv and readme file

### Screenshots or Videos

### Additional Details

### Checklist

- [ ] My code follows the current [project structure](https://github.com/yashasvini121/predictive-calc/blob/master/docs/project-structure.md)
- [ ] I have thoroughly reviewed and updated the `requirements.txt` file to include any new packages
- [ ] The `predict.py` file includes a properly implemented `model_details()` function, or the notebook contains this function to print a detailed model report. **The model will not be accepted without this function**, as it is essential for generating the necessary model details.
- [ ] I have added relevant tests (if necessary).
- [ ] I have added comments in the code where needed.
- [ ] This PR is submitted under **Hacktoberfest**.
- [ ] This PR is submitted under **GirlScript Summer of Code (GSSoC-Extd)**.

2024-11-07 16:12 UTC, yashasvini121 commented on models/customer-churn-prediction/README.md
Remove this file. Add the relevant model details to `App.py`

2024-11-07 16:14 UTC, yashasvini121 requested changes
Please ensure your work aligns with the project structure and review the tutorial thoroughly. Your current work does not follow the specified structure. Refer to the docs for guidance.

2024-11-07 18:05 UTC, Absk024 commented
i would like to contribute @yashasvini121

2024-11-08 11:42 UTC, Dharun235 commented
@yashasvini121 I have made the changes as per tutorial.md.

2026-02-15 23:49 UTC, closed without merging