Added Stress Level Detection Model
yashasvini121/predictive-calc pull request #29
Opened 2024-10-02 13:23 UTC by J-B-Mugundh

Description:
This pull request introduces a new feature for detecting mental stress levels based on social media interactions using a Random Forest model. The implementation includes the following changes:

Model Integration: Integrated the trained random_forest_model.joblib to predict stress levels based on user inputs.

Prediction Logic: Implemented a function to assess stress levels and provide tailored advice based on the predicted value:

- Low Stress (less than 1.5): Suggests maintaining a balanced lifestyle.
- Moderate Stress (between 1.5 and 3.5): Recommends taking breaks and practicing stress relief techniques.
- High Stress (greater than 3.5): Advises seeking professional help or implementing stress management strategies.

Testing:
The feature has been tested locally, ensuring that predictions return accurate stress levels and corresponding advice based on various input scenarios.

Next Steps:
Review and provide feedback on the implementation.
Consider any additional features or improvements for user experience.

Related Issue:
#25

Screenshots: 

![image](https://github.com/user-attachments/assets/90586c10-e74a-42fb-b626-969a5c794d48)
![image](https://github.com/user-attachments/assets/73c25d15-bd64-4dc4-9eed-770de47479a7) 

Thank you for reviewing this PR!

2024-10-02 13:24 UTC, J-B-Mugundh commented
@yashasvini121 Please review the PR and let me know if it needs any improvements. Thank you 😊

2024-10-02 15:01 UTC, yashasvini121 requested changes
The code is totally fine, but some minor changes would improve it further. Sync your fork before making any updates as well.

2024-10-02 15:19 UTC, J-B-Mugundh commented on models/stress_level_detect/model.py
> +model = load('models/stress_level_detect/random_forest_model.joblib')
> * You have used a pre-trained model. If you trained it yourself, please add the Jupyter notebook or include the training process in the `model.py` file.
> * Additionally, if you have the dataset, please include that as well.
> * If you are using a pre-trained model from an external source, please mention the source of the model. Any references or URLs in a comment would help.

I'll add the notebook file where I trained.

2024-10-02 15:36 UTC, J-B-Mugundh commented on models/stress_level_detect/predict.py
> This file lacks the `model_details()` function. **If possible**, please add the model evaluation or provide a model description that includes its source, any relevant references, and additional details.
> 
> If this requires updates in the `page_handler.py`, you can leave it as is or make the necessary fixes.

Will it be fine if I can add the graphs which I have in notebook like?

![image](https://github.com/user-attachments/assets/d0f799ca-9af3-4191-83eb-dce9fc225db0)

2024-10-02 15:53 UTC, yashasvini121 commented on models/stress_level_detect/predict.py
Yes, you can include graphs, but please only add those that directly explain the problem statement, as this particular graph isn't very helpful. Alternatively, if your updates aren't general to all models, you could create a custom class from `PageHandler` in `Stress_Level_Detector.py` and add your required functions there.

Additionally, if you have a useful and relevant notebook, please add it to the `notebooks/` folder.

2024-10-02 16:05 UTC, J-B-Mugundh commented on models/stress_level_detect/predict.py
I don't find much useful graphs around here!

2024-10-03 03:16 UTC, J-B-Mugundh commented
@yashasvini121 Is it fine now or should I add or change anything more?

2024-10-03 09:52 UTC, yashasvini121 approved these changes

2024-10-03 09:53 UTC, merged

2024-10-03 10:02 UTC, yashasvini121 commented
One final piece of feedback: avoid working directly on the master branch. Instead, create a new branch for each issue to prevent potential merge conflicts.

2024-10-03 10:08 UTC, J-B-Mugundh commented
> Great!! One final piece of feedback: avoid working directly on the master branch. Instead, create a new branch for each issue to prevent potential merge conflicts.

Sure! I hadn't thought of that.. Thanks so much for bringing it up! 😊