Create requuirments.txt
yashasvini121/predictive-calc pull request #42
Opened 2024-10-04 08:12 UTC by priyans877

2024-10-06 15:41 UTC, priyans877 commented
@yashasvini121 i had updated my project but i did't hear any reply from our side kindly merge after checking it

2024-10-07 09:29 UTC, yashasvini121 requested changes
Please update your project to align with the overall project structure as outlined in the documentation. The expected result is a properly structured page for your model within the project, following the provided guidelines.

2024-10-07 09:29 UTC, yashasvini121 commented on models/Azure_Review_analyzer/speech_recognition.py
Please update the files that use `streamlit` so that the final structure has only one file in the `pages/` directory responsible for creating the Streamlit page (e.g., `pages/Azure_Review_Analyzer.py`). Refactor the other files to handle specific tasks or components, and ensure they are imported into this main file for a cleaner and more organized structure.

2024-10-07 09:29 UTC, yashasvini121 commented on models/Azure_Review_analyzer/text_sentimet.py
Please update the files that use `streamlit` so that the final structure has only one file in the `pages/` directory responsible for creating the Streamlit page (e.g., `pages/Azure_Review_Analyzer.py`). Refactor the other files to handle specific tasks or components, and ensure they are imported into this main file for a cleaner and more organized structure.

2024-10-11 10:42 UTC, yashasvini121 commented
@priyans877, Please reopen this PR once you've completed your updates. I am closing it for now.

2024-10-11 10:42 UTC, closed without merging