Implement logging system in logger.py and integrate it in App.py
yashasvini121/predictive-calc pull request #63
Opened 2024-10-05 13:57 UTC by SatyaD012

### Description
This pull request implements a logging system using a dedicated logger class in `logger.py`. The logging configuration includes:
- **Log file**: The default log file is `app.log` located in the root directory.
- **Log level**: The minimum logging level is set to `INFO`, with options for other levels such as WARNING and ERROR.

### Changes Made
- Created `logger.py` with logging configuration.
- Integrated logging into `App.py` to track application startup and shutdown events.
- Added a `logs` folder to store log files (added to `.gitignore` for version control).

### Screenshot
Attached is a screenshot of the log output demonstrating that the logging system is working correctly.

![Screenshot 2024-10-05 191811](https://github.com/user-attachments/assets/7c80cbc5-ce5b-49af-9215-f651fa70f176)

2024-10-05 14:47 UTC, yashasvini121 requested changes
The altered files are showing up in binary format. Please address this issue to ensure that the files are in the correct format.

Additionally, it seems that several requirements outlined in issue #53 are missing. Please revisit the instructions and make sure to follow them thoroughly.

2024-10-05 14:47 UTC, yashasvini121 commented on logger.py
You need to create a proper Logger Class as mentioned in the #53.

2024-10-05 14:47 UTC, yashasvini121 commented on App.py
It appears that all the code has been removed from `App.py`. Please restore the necessary code and also implement logging at relevant points.

2024-10-06 13:20 UTC, yashasvini121 commented
@SatyaD012, updates?

2024-10-06 20:41 UTC, SatyaD012 commented
Hii 
I make some changes and  also added code to app.py .I will update it to you soon..

2024-10-08 16:50 UTC, closed without merging