Add Real-Time Emotion Detector (EmotionIQ)
yashasvini121/predictive-calc pull request #70
Opened 2024-10-05 20:58 UTC by ChitteshKumar

I have developed a real-time emotion detector, which I named **EmotionIQ**. This tool leverages a CNN model, OpenCV techniques, and Streamlit to successfully detect facial expressions and classify emotions in real-time.

**EmotionIQ Implementation:**
- I added a new folder to the models directory, named emotion_detector, which contains the necessary dataset and model files for EmotionIQ.
- The dataset used comes from Kaggle: [Face Expression Recognition Dataset](https://www.kaggle.com/datasets/jonathanoheix/face-expression-recognition-dataset). I used this dataset to train the CNN model using TensorFlow, with the model being implemented in a .ipynb file.
- The trained model is now used within the driver.py file, where it processes real-time video captured from the camera, detects faces using OpenCV, and classifies the emotions. Additionally, warnings are displayed to the user, notifying them when the camera is being accessed.

**Integration into the Platform:**
As most of the code in the project was geared towards form-based interactions and making predictive calculators, I introduced a new function called render_detector() in the page_handler.py file. This function allows seamless integration of emotion detectors (or similar applications) into the platform, enabling anyone to easily add this feature in the future.

Files Modified:
- models/emotion_detector: 
    - Contains the dataset and the trained CNN model.
    - Model is built in a TensorFlow-based .ipynb file.
- driver.py:
    - Loads and runs the model, utilizing OpenCV for facial detection and real-time camera feed for emotion analysis.
- page_handler.py:
    - Added the render_detector() function to allow integration of emotion detection functionality into the platform.

By merging this, the project will now support a fully-functional, real-time emotion detection system, expanding the predictive capabilities beyond just calculators.

**Expected Outcome:**
The EmotionIQ feature will enable real-time emotion detection using a CNN model, enhancing user engagement with live facial expression analysis via webcam. The new render_detector() function in page_handler.py allows seamless integration of real-time detection features, improving modularity and reusability for future development.

2024-10-05 21:10 UTC, ChitteshKumar commented
Hi @yashasvini121, I have completed the assigned task #31 . And created a pull request, kindly check it and provide feedback.
Looking forward to get the request accepted

Thank you

2024-10-06 11:33 UTC, yashasvini121 requested changes
Please upload your data folder in a ZIP format, as we will only be using the saved model at the end.

2024-10-06 12:12 UTC, ChitteshKumar commented
> Please upload your data folder in a ZIP format, as we will only be using the saved model at the end. (Please confirm this, as I haven't checked the code.)

okay, I'll put the dataset into zip. I a bit unsure how to do that, should I close the PR and raise it again? can you tell me the procedure.

2024-10-06 12:15 UTC, yashasvini121 commented
@ChitteshKumar, just continue working on this branch; your changes will be reflected automatically.

2024-10-06 12:56 UTC, ChitteshKumar commented
> @ChitteshKumar, just continue working on this branch; your changes will be reflected automatically.
> 
> Eg: You recently merged `master` into this pr related branch, those changes are now showing in the PR, look at the timeline, above.

okay I have tried doing. Please check it and tell me if its correct or not.

2024-10-07 09:46 UTC, ChitteshKumar commented
hi @yashasvini121 , I would just like to remind you to kindly check this merge and complete it.

2024-10-08 04:37 UTC, yashasvini121 requested changes
Look into this error:
![image](https://github.com/user-attachments/assets/5a1123b1-a79c-4eba-b471-6faafab90af9)

P.S.: Your model mostly returns a surprise emotion.

2024-10-08 04:37 UTC, yashasvini121 commented on models/emotion_detector/.DS_Store
For my general knowledge, could you please explain the purpose of the `.DS_Store` file in this project? Or else, If it’s not necessary, kindly remove it.

2024-10-08 04:37 UTC, yashasvini121 commented on models/.DS_Store
For my general knowledge, could you please explain the purpose of the `.DS_Store` file in this project? Or else, If it’s not necessary, kindly remove it.

2024-10-08 09:35 UTC, ChitteshKumar commented on models/.DS_Store
I'll remove it as it just contains stores custom attributes of its containing folder, such as folder view options, icon positions, and other visual information. It is automatically generated in Mac.

2024-10-08 09:39 UTC, ChitteshKumar commented on models/emotion_detector/driver.py
> +
I want it to be there.

2024-10-08 09:39 UTC, ChitteshKumar commented on requirements.txt
> +streamlit
okay I'll do it

2024-10-08 09:52 UTC, ChitteshKumar commented on models/emotion_detector/driver.py
> +model = load_model('/Users/chittesh/GSSoC/predictive-calc/models/emotion_detector/saved_models/best_model.keras')
Okay I will do it. Apologise for not changing that

2024-10-08 14:23 UTC, ChitteshKumar commented
> Look into this error: ![image](https://private-user-images.githubusercontent.com/100478608/374407559-5a1123b1-a79c-4eba-b471-6faafab90af9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzOTc2MDcsIm5iZiI6MTcyODM5NzMwNywicGF0aCI6Ii8xMDA0Nzg2MDgvMzc0NDA3NTU5LTVhMTEyM2IxLWE3OWMtNGViYS1iNDcxLTZmYWFmYWI5MGFmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQxNDIxNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MzIzMGQxZWZhMDRlMTBhYTYxYmNjZDZiMzY5OTM1NzNmZDg1OGJjNDY5MTI2YmQ0NzVjOTczMWNjNTIzYTY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.j0Oh-Z_AcY1P7FyuvZ3VQewevcvES_2Zb5I4XDLQU_w)
> 
> P.S.: Your model mostly returns a surprise emotion.

thank you so much for pointing the error out. I have tried fixing the error, can you check. Also the model is bit simple, so once this gets merged (if you allow), then I can create a new issue and work on it. Looking forward to hear from you soon.

2024-10-10 09:50 UTC, ChitteshKumar commented
@yashasvini121 , hi can you review this please accept this.

2024-10-10 09:51 UTC, yashasvini121 commented
Will be reviewed by today

2024-10-11 08:16 UTC, yashasvini121 commented
Sorrry for the delay, for now, please instead of `yashasvini121:master`, create a pr to push to `yashasvini121:emotion-detector` branch.

2024-10-11 11:28 UTC, closed without merging